import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
     subsets:['latin'],
     style : 'normal',
     weight : '400'})

export const metadata: Metadata = {
  title: "Hackathon Preparation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className= {`${poppins.className} max-w-[1440px] mx-auto`} >{children}</body>
    </html>
  );
}
